### ISSUE TITLE
exception 'ReflectionException' with message 'Class robregonm\pdf\PdfResponseFormatter does not exist

### ISSUE THREAD

**Issue by hdushku** [kartik-v/mpdf#13]
An Error occurred while handling another error:
exception 'ReflectionException' with message 'Class robregonm\pdf\PdfResponseFormatter does not exist' in /var/sentora/hostdata/zadmin/public_html/.../vendor/yiisoft/yii2/di/Container.php:422
Previous exception:
exception 'yii\base\ErrorException' with message 'file_put_contents(/var/sentora/hostdata/zadmin/public_html/.../vendor/mpdf/mpdf/ttfontdata/xbriyaz.GSUBGPOStables.dat): failed to open stream: Permission denied' in /var/sentora/hostdata/zadmin/public_html/.../vendor/mpdf/mpdf/classes/ttfontsuni.php:1264

**Comment by kartik-v** [comment]
You would need to report this with the related extension's author `robregonm\pdf`... this has nothing to do with this extension.
