### ISSUE TITLE
PHP 7.1: Illegal string offset 'ID'

### ISSUE THREAD

**Issue by danik2592** [kartik-v/mpdf#18]
Error has shown after php update to 7.1 version. On 7.0 it works fine.
 ```php
        $mpdf = (new Pdf($this->pdfParams))->api;
        $mpdf->setAutoTopMargin = 'stretch';
        $mpdf->setAutoBottomMargin = 'stretch';
        $mpdf->SetFooter($footer); // error's here 
        $mpdf->WriteHTML($html);
        return $mpdf;
```
![default](https://cloud.githubusercontent.com/assets/14977920/21340846/e670c9c6-c6aa-11e6-9d60-1264ca8d5f7b.PNG)

**Comment by StalkAlex** [comment]
+1

**Comment by danik2592** [comment]
Fix in https://github.com/kartik-v/mpdf/commit/01689a83d4e428ef55645d0d0ff1d2f6268047a4
