### ISSUE TITLE
Malware in the code?

### ISSUE THREAD

**Issue by atinius** [kartik-v/mpdf#8]
Hi!
My web hosting provider says that the file:
example61_new_mPDF_v6-0_features.pdf
contains a malware and try to send out emails. I don't see any problem with the code, but they insist that there is a harmful part and the virustotal also says the file is infected. 
https://www.virustotal.com/hu/file/470ebc36ae8159aa9e17bed0d580c9a52634142c50fb3ab1728526b01ba9ef5e/analysis/1454593476/
Could you please  tell me if you have any idea why is the false positive?

**Comment by kartik-v** [comment]
I have no idea really. This is from the mpdf repository and you may try to contact the mpdf author and community to see if you get any information or help on this.

**Comment by atinius** [comment]
I'll do that, thank you for the answer and for your work.
